name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest  # Using Windows environment; you can switch to 'ubuntu-latest' if preferred

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\activate  # Use Windows style; change to 'source venv/bin/activate' for Linux
        pip install -r requirements.txt
